name: Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Haskell toolchain(GHC & Cabal)
        uses: haskell-actions/setup@v2

      - name: Initialize Cabal
        run: cabal update
      
      - name: Build Rhino Compiler
        run: cabal build
